version: '3'
services:

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "fublog"
      POSTGRES_PASSWORD: "8!06"
      POSTGRES_DB: "fublog"
    ports:
      - "5020:5432"

  app:
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 5000
      SERVER_API_PATH: /api
      CLIENT_PORT: 5010
      CLIENT_URL: http://localhost
      CLIENT_BASE_URL: http://localhost:5010
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: fublog
      DATABASE_PW: 8!06
      DATABASE_NAME: fublog
      NODE_ENV: production
    image: fublog_app:latest
    ports:
      - "5000:5000"
