version: '3'
services:

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5020:5432"
    environment:
      POSTGRES_USER: "fublog"
      POSTGRES_PASSWORD: "8!06"
      POSTGRES_DB: "fublog"
