version: '3'
services:

  postgres-dev:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
      args:
        language: de_DE
    environment:
      POSTGRES_USER: "fublog"
      POSTGRES_PASSWORD: "8!06"
      POSTGRES_DB: "fublog"
    ports:
      - "5020:5432"
