# Docker compose file that demonstrates how to start the blog
# It uses the version from the `main` branch of GitHub.com/fumiX/fuBlog
version: '3'

services:
  postgres:
    image: ghcr.io/fumix/fublog-postgres:main-de_DE
    env_file: .env
    environment:
      # Example
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - fublog_postgres_data:/var/lib/postgresql/data
  app:
    image: ghcr.io/fumix/fublog-app:main
    env_file: .env
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
    networks:
      - default
      - outside
networks:
  # The docker network that connects the app with the outside world (put e.g. an nginx container in this network)
  outside:
    external: true
volumes:
  fublog_postgres_data:
