name: build

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run check-packages

  build-common:
    needs: basic-tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: common/dist/
          key: common_dist-${{ runner.os }}-${{ hashFiles('.node-version', 'package-lock.json') }}-${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run lint --workspace common
      - run: npm run build --workspace common

  build-app:
    needs: build-common
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        workspace: [ client, server ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: common/dist/
          key: common_dist-${{ runner.os }}-${{ hashFiles('.node-version', 'package-lock.json') }}-${{ github.sha }}
      - uses: actions/cache@v3
        with:
          path: |
            client/dist/
            server/dist/
          key: app_dist-${{ runner.os }}-${{ hashFiles('.node-version', 'package-lock.json') }}-${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run lint --workspace ${{ matrix.workspace }}
      - run: npm run build --workspace ${{ matrix.workspace }}

  publish:
    needs: build-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: common/dist/
          key: common_dist-${{ runner.os }}-${{ hashFiles('.node-version', 'package-lock.json') }}-${{ github.sha }}
      - uses: actions/cache@v3
        with:
          path: |
            client/dist/
            server/dist/
          key: app_dist-${{ runner.os }}-${{ hashFiles('.node-version', 'package-lock.json') }}-${{ github.sha }}
      - run: |
          ls -R *
          cp -r server/dist/* docker/app/
          cp -rT client/dist/ docker/app/public/
          cp server/package.json docker/app/
          mkdir -p "docker/app/node_modules/@fumix"
          cp -r -T common/ "docker/app/node_modules/@fumix/fu-blog-common"
          cd docker/app/
          npm install
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-app
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-db-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-postgres
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/postgres
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
